// app/components/restaurent/RestaurentSection.vue
<template>
  <section class="popular-hotels-section" style="margin-top: 150px;">
    <div class="container">
      <div class="section-header">
        <h2>Explore Nearby Restaurants</h2>
        <p>
          Discover the best dining spots just around the corner. Savor local
          flavors and unique cuisines that await you!
        </p>
      </div>

      <div class="slider-container">
        <!-- Prev Button -->
        <button class="slider-arrow prev-arrow" @click="prevSlide">
          <svg width="30" height="30" viewBox="0 0 30 30" fill="none">
            <path
              d="M18.75 23.75L10 15L18.75 6.25"
              stroke="#003D6F"
              stroke-width="3"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
          </svg>
        </button>

        <!-- Dynamic Restaurant Cards section -->
        <div class="slider-grid">
          <div
            v-for="(restaurant, index) in visibleRestaurants"
            :key="index"
            class="hotel-card"
          >
            <img 
              :src="restaurant.image_url ?? 'https://admin.clickhospitals.com/dumy.jpg'" 
              :alt="restaurant.name" 
              loading="lazy"
              :class="{ 'image-loading': !imageLoaded[restaurant.id] }"
              @load="imageLoaded[restaurant.id] = true"
              @error="imageLoaded[restaurant.id] = true"
            />
            <div class="card-content">
              <h3>
                {{ useTruncateText(restaurant?.name || "", 20) }}
                <span class="rating">
                  {{ restaurant.rating }}
                  <span class="star">★</span>
                </span>
              </h3>
              <a
                :href="restaurant.google_map_location"
                class="btn btn-sm btn-light mt-2"
              >
                <Icon name="material-symbols:location-on-outline"
                  style="color:#053862; margin-right:5px; font-size: 18px;" />
                Google Map
              </a>
            </div>
          </div>
        </div>

        <!-- Next Button -->
        <button class="slider-arrow next-arrow" @click="nextSlide">
          <svg width="30" height="30" viewBox="0 0 30 30" fill="none">
            <path
              d="M11.25 23.75L20 15L11.25 6.25"
              stroke="#003D6F"
              stroke-width="3"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
          </svg>
        </button>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, computed, reactive, onMounted, onBeforeUnmount } from "vue"

// Props
const props = defineProps({
  restaurants: {
    type: Array,
    required: true
  }
})

// Current index of slider
const currentIndex = ref(0)

// Track image loading for blur effect
const imageLoaded = reactive({})

// ---------------- Dynamic items per page ----------------
const itemsPerPage = ref(5)

function updateItemsPerPage() {
  const width = window.innerWidth
  if (width < 768) {
    // Mobile
    itemsPerPage.value = 1
  } else if (width < 1024) {
    // Tablet
    itemsPerPage.value = 2
  } else {
    // Desktop
    itemsPerPage.value = 5
  }

  // Ensure currentIndex is valid after resizing
  if (currentIndex.value + itemsPerPage.value > props.restaurants.length) {
    currentIndex.value = Math.max(0, props.restaurants.length - itemsPerPage.value)
  }
}

// Call on mounted and listen for resize
onMounted(() => {
  updateItemsPerPage()
  window.addEventListener("resize", updateItemsPerPage)
})

onBeforeUnmount(() => {
  window.removeEventListener("resize", updateItemsPerPage)
})

// ---------------- Compute visible restaurants ----------------
const visibleRestaurants = computed(() => {
  return props.restaurants.slice(
    currentIndex.value,
    currentIndex.value + itemsPerPage.value
  )
})

// ---------------- Slider navigation ----------------
function nextSlide() {
  if (currentIndex.value + itemsPerPage.value < props.restaurants.length) {
    currentIndex.value++
  }
}

function prevSlide() {
  if (currentIndex.value > 0) {
    currentIndex.value--
  }
}
</script>

// src/components/restaurent/RestaurentSection.tsx
'use client';

import { useSlider } from '@/hooks/useSlider';
import { truncateText } from '@/lib/helpers';

interface NearbyItem {
	id: number;
	name?: string;
	title?: string;
	image_url?: string;
	google_map_location?: string;
}

export default function RestaurentSection({ restaurants }: { restaurants: NearbyItem[] }) {
	const { currentIndex, slidesPerView, maxIndex, prevSlide, nextSlide } = useSlider(restaurants.length, [
		{ minWidth: 992, slides: 5 },
		{ minWidth: 768, slides: 2 },
		{ minWidth: 0, slides: 1 },
	]);

	if (!restaurants.length) return null;

	return (
		<section id="restaurants" className="my-5 popular-hotels-section">
			<div className="section-header">
				<h2>Explore Nearby Restaurants</h2>
				<p>
					Discover the best dining spots just around the corner. Savor local
					flavors and unique cuisines that await you!
				</p>
			</div>
			<div className="slider-container">
				<button className="slider-arrow prev-arrow" onClick={prevSlide} disabled={currentIndex === 0}>&#10094;</button>
				<div className="slider-wrapper">
					<div className="slider-track" style={{ transform: `translateX(-${currentIndex * (100 / slidesPerView)}%)` }}>
						{restaurants.map((item) => (
							<div key={item.id} className="card hotel-card m-2">
								<img src={item.image_url || 'https://admin.clickhospitals.com/dumy.jpg'} className="card-img-top" alt={item.name || item.title} />
								<div className="card-body">
									<h6>{truncateText(item.name || item.title || 'Restaurant', 40)}</h6>
									{item.google_map_location && <a href={item.google_map_location} target="_blank" rel="noreferrer" className="btn btn-sm btn-light">Map</a>}
								</div>
							</div>
						))}
					</div>
				</div>
				<button className="slider-arrow next-arrow" onClick={nextSlide} disabled={currentIndex >= maxIndex}>&#10095;</button>
			</div>
		</section>
	);
}
