// flyfrontend/src/components/Header.tsx
'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useGeneralStore } from '@/stores/general';
import { useHospitalStore } from '@/stores/hospital';
import { apiFetch } from '@/lib/api';
import type { Treatments } from '@/lib/types';

export default function Header() {
	const pathname = usePathname();
	const [isMenuOpen, setIsMenuOpen] = useState(false);
	const [activeDropdown, setActiveDropdown] = useState<string | null>(null);
	const [imageLoaded, setImageLoaded] = useState(false);
	const [citiesData, setCitiesData] = useState<Record<number, { id: number; name: string }[]>>({});
	const [activeCountry, setActiveCountry] = useState<number | null>(null);
	const [subTreatments, setSubTreatments] = useState<Record<number, Treatments[]>>({});
	const [activeTreatment, setActiveTreatment] = useState<number | null>(null);
	const [isMobile, setIsMobile] = useState(false);

	const treatments = useGeneralStore((s) => s.treatments);
	const destinations = useGeneralStore((s) => s.destinations);
	const fetchTreatments = useGeneralStore((s) => s.fetchTreatments);
	const fetchDestination = useGeneralStore((s) => s.fetchDestination);
	const loadCountries = useHospitalStore((s) => s.loadCountries);

	useEffect(() => {
		const checkMobile = () => setIsMobile(window.innerWidth < 992);
		checkMobile();
		window.addEventListener('resize', checkMobile);
		return () => window.removeEventListener('resize', checkMobile);
	}, []);

	useEffect(() => {
		setIsMenuOpen(false);
		setActiveDropdown(null);
	}, [pathname]);

	useEffect(() => {
		void fetchTreatments();
		void fetchDestination();
		void loadCountries();
	}, [fetchTreatments, fetchDestination, loadCountries]);

	const toggleMenu = () => setIsMenuOpen(!isMenuOpen);
	const toggleDropdown = (name: string) => setActiveDropdown(activeDropdown === name ? null : name);
	const closeAllMenus = () => {
		setIsMenuOpen(false);
		setActiveDropdown(null);
	};

	const handleCountryHover = async (countryId: number) => {
		setActiveCountry(countryId);
		if (!citiesData[countryId]) {
			try {
				const res = await apiFetch<{ data?: { id: number; name: string }[] }>(`countries/${countryId}/cities`);
				setCitiesData((prev) => ({ ...prev, [countryId]: res.data ?? [] }));
			} catch {
				setCitiesData((prev) => ({ ...prev, [countryId]: [] }));
			}
		}
	};

	const handleTreatmentHover = async (treatmentId: number) => {
		setActiveTreatment(treatmentId);
		if (!subTreatments[treatmentId]) {
			try {
				const res = await apiFetch<{ data?: Treatments[] }>('sub-treatments', { params: { parent_id: treatmentId } });
				setSubTreatments((prev) => ({ ...prev, [treatmentId]: res.data ?? [] }));
			} catch {
				setSubTreatments((prev) => ({ ...prev, [treatmentId]: [] }));
			}
		}
	};

	return (
		<header className="container-fluid bg-white shadow-sm sticky-top">
			<nav className="navbar navbar-expand-lg">
				<div className="container">
					<Link href="/" className="navbar-brand" onClick={closeAllMenus}>
						<img
							src="/assets/img/logo.png"
							className={`logo${!imageLoaded ? ' image-loading' : ''}`}
							alt="ClickHospitals Logo"
							onLoad={() => setImageLoaded(true)}
							onError={() => setImageLoaded(true)}
						/>
						<span>ClickHospitals</span>
					</Link>

					<button id="navbarToggler" className="navbar-toggler" type="button" aria-label="Toggle navigation" onClick={toggleMenu}>
						<i className={`bi ${isMenuOpen ? 'bi-x-lg' : 'bi-list'}`} style={{ fontSize: 28 }} />
					</button>

					<div id="navbarCollapse" className={`navbar-collapse${isMenuOpen ? ' show' : ''}`}>
						<ul className="navbar-nav mx-auto align-items-center">
							<li className="nav-item dropdown">
								<div className="dropdown-wrapper">
									<button className="dropdown-toggle d-flex align-items-center nav-link w-100 border-0 bg-transparent" onClick={() => toggleDropdown('destination')}>
										Destination
										<i className={`bi ms-1 ${activeDropdown === 'destination' ? 'bi-chevron-up' : 'bi-chevron-down'}`} />
									</button>
									{activeDropdown === 'destination' && destinations.length > 0 && (
										<div className="main-dropdown-menu shadow-sm border rounded">
											<div className="procedure-container">
												<ul className="main-treatment-list mb-0">
													{destinations.slice(0, 5).map((country) => (
														<li
															key={country.id}
															className="treatment-item"
															onMouseEnter={() => !isMobile && handleCountryHover(country.id)}
														>
															<div className="d-flex align-items-center justify-content-between w-100">
																<Link
																	href={`/hospitals?country_id=${country.id}`}
																	className={`treatment-link flex-grow-1${activeCountry === country.id ? ' active' : ''}`}
																	onClick={closeAllMenus}
																>
																	<div className="country-info">
																		<span className="treatment-name">{country.country_name || country.name}</span>
																	</div>
																	{isMobile ? (
																		<button className="btn btn-link p-2" onClick={(e) => { e.preventDefault(); handleCountryHover(country.id); }}>
																			<i className={`bi ${activeCountry === country.id ? 'bi-chevron-up' : 'bi-chevron-right'}`} />
																		</button>
																	) : (
																		<i className="bi bi-chevron-right chevron-icon" />
																	)}
																</Link>
															</div>
															{!isMobile && activeCountry === country.id && citiesData[country.id]?.length > 0 && (
																<div className="subtreatment-dropdown">
																	<ul className="subtreatment-list mb-0">
																		{citiesData[country.id].map((city) => (
																			<li key={city.id}>
																				<Link href={`/hospitals?country_id=${country.id}&city_id=${city.id}`} onClick={closeAllMenus}>
																					{city.name}
																				</Link>
																			</li>
																		))}
																	</ul>
																</div>
															)}
														</li>
													))}
												</ul>
											</div>
										</div>
									)}
								</div>
							</li>

							<li className="nav-item dropdown">
								<div className="dropdown-wrapper">
									<button className="dropdown-toggle d-flex align-items-center nav-link w-100 border-0 bg-transparent" onClick={() => toggleDropdown('procedure')}>
										Procedure
										<i className={`bi ms-1 ${activeDropdown === 'procedure' ? 'bi-chevron-up' : 'bi-chevron-down'}`} />
									</button>
									{activeDropdown === 'procedure' && treatments.length > 0 && (
										<div className="main-dropdown-menu shadow-sm border rounded">
											<ul className="main-treatment-list mb-0">
												{treatments.slice(0, 8).map((treatment) => (
													<li
														key={treatment.id}
														className="treatment-item"
														onMouseEnter={() => !isMobile && handleTreatmentHover(treatment.id)}
													>
														<Link
															href={`/subprocedure/${treatment.id}?name=${encodeURIComponent(treatment.name)}`}
															className="treatment-link"
															onClick={closeAllMenus}
														>
															{treatment.name}
															<i className="bi bi-chevron-right" />
														</Link>
														{!isMobile && activeTreatment === treatment.id && subTreatments[treatment.id]?.length > 0 && (
															<div className="subtreatment-dropdown">
																<ul className="subtreatment-list mb-0">
																	{subTreatments[treatment.id].map((sub) => (
																		<li key={sub.id}>
																			<Link href={`/all-procedure/${encodeURIComponent(sub.name)}`} onClick={closeAllMenus}>
																				{sub.name}
																			</Link>
																		</li>
																	))}
																</ul>
															</div>
														)}
													</li>
												))}
											</ul>
										</div>
									)}
								</div>
							</li>

							<li className="nav-item">
								<Link href="/about" className="nav-link" onClick={closeAllMenus}>About</Link>
							</li>
							<li className="nav-item">
								<Link href="/partner" className="nav-link" onClick={closeAllMenus}>Partner</Link>
							</li>
						</ul>

						<div className="d-flex align-items-center gap-3">
							<span className="d-none d-lg-inline text-muted small">
								<i className="bi bi-telephone me-1" /> +1(734)-447-5890
							</span>
							<Link href="/contact" className="btn btn-primary" onClick={closeAllMenus}>Contact</Link>
						</div>
					</div>
				</div>
			</nav>
		</header>
	);
}

// app/components/Header.vue
<template>
  <header class="container-fluid bg-white shadow-sm sticky-top">
    <nav class="navbar navbar-expand-lg">
      <div class="container">
        <!-- Logo -->
        <NuxtLink to="/" class="navbar-brand" exact-active-class="active">
          <img
            src="~assets/img/logo.png"
            class="logo"
            alt="ClickHospitals Logo"
            loading="eager"
            :class="{ 'image-loading': !imageLoaded }"
            @load="imageLoaded = true"
            @error="imageLoaded = true"
          />
          <span>ClickHospitals</span>
        </NuxtLink>

        <!-- Navbar Toggler -->
        <button
          id="navbarToggler"
          class="navbar-toggler"
          type="button"
          aria-label="Toggle navigation"
          @click="toggleMenu"
        >
          <!-- Hamburger -->
          <Icon v-if="!isMenuOpen" name="mdi:menu" size="28" />

          <!-- Close -->
          <Icon v-else name="mdi:close" size="28" />
        </button>

        <!-- Collapsible Menu -->
        <div id="navbarCollapse" class="navbar-collapse">
          <ul class="navbar-nav mx-auto align-items-center">
            <!-- Destination Dropdown -->
            <li class="nav-item dropdown" v-if="destinations.length">
              <Dropdown>
                <DropdownToggle class="dropdown-toggle d-flex align-items-center nav-link">
                  Destination
                  <Icon name="carbon:chevron-down" />
                </DropdownToggle>
                <DropdownMenu>
                  <DropdownItem
                    v-for="destination in destinations.slice(0,3)"
                    :key="destination.id"
                    as="div"
                  >
                    <NuxtLink :to="`/hospitals?country_id=${destination.id}`">
                      {{ destination.country_name || destination.name }}
                    </NuxtLink>
                  </DropdownItem>
                  <DropdownItem>
                    <NuxtLink to="/destinations">See All</NuxtLink>
                  </DropdownItem>
                </DropdownMenu>
              </Dropdown>
            </li>

            <!-- Procedure Dropdown -->
            <li class="nav-item dropdown" v-if="treatments.length">
              <Dropdown>
                <DropdownToggle class="dropdown-toggle d-flex align-items-center nav-link">
                  Procedure
                  <Icon name="carbon:chevron-down" />
                </DropdownToggle>
                <DropdownMenu>
                  <DropdownItem
                    v-for="treatment in treatments.slice(0,3)"
                    :key="treatment.id"
                    as="div"
                  >
                    <NuxtLink
                      :to="`/subprocedure/${treatment.id}?name=${encodeURIComponent(treatment.name)}`"
                    >
                      {{ treatment.name }}
                    </NuxtLink>
                  </DropdownItem>
                  <DropdownItem>
                    <NuxtLink to="/procedure">See All</NuxtLink>
                  </DropdownItem>
                </DropdownMenu>
              </Dropdown>
            </li>

            <!-- Links -->
            <li class="nav-item">
              <NuxtLink to="/about" class="nav-link" exact-active-class="active">
                About us
              </NuxtLink>
            </li>
            <li class="nav-item">
              <NuxtLink to="/partner" class="nav-link" exact-active-class="active">
                Become a Partner
              </NuxtLink>
            </li>
          </ul>

          <!-- Support & Contact -->
          <div class="d-flex flex-column flex-lg-row align-items-lg-center mt-3 mt-lg-0 supportandbtn">
            <div class="support-info me-lg-3 text-lg-end mb-2 mb-lg-0">
              <span
                class="d-block p-2 mb-1"
                style="background:#F5F5F5; border-radius:6px;"
              >
                Our 24/7 Support
                <Icon name="carbon:arrow-right" />
              </span>
              <a href="tel:+17344475890" class="text-decoration-none">
                +1(734)-447-5890
              </a>
            </div>
            <NuxtLink class="btn btn-primary" to="/contact">
              Contact Us
            </NuxtLink>
          </div>
        </div>
      </div>
    </nav>
  </header>
</template>

<script setup lang="ts">
import { computed, ref, watch, onMounted } from 'vue'
import { useGeneralStore } from '~/stores/general'
import { useRouter } from 'vue-router'

const router = useRouter()

router.afterEach(() => {
  isMenuOpen.value = false
  const collapse = document.getElementById('navbarCollapse')
  if (collapse) collapse.style.display = 'none'
})

const store = useGeneralStore()
const imageLoaded = ref(false)
const isMenuOpen = ref(false)

// Fetch data
if (store.treatments.length === 0) {
  await useAsyncData('treatments', () => store.fetchTreatments())
}
if (store.destinations.length === 0) {
  await useAsyncData('destinations', () => store.fetchDestination())
}

const treatments = computed(() => store.treatments)
const destinations = computed(() => store.destinations)

// Toggle menu
function toggleMenu() {
  const collapse = document.getElementById('navbarCollapse')
  if (!collapse) return

  isMenuOpen.value = !isMenuOpen.value
  collapse.style.display = isMenuOpen.value ? 'block' : 'none'
}

// Mobile default
onMounted(() => {
  const collapse = document.getElementById('navbarCollapse')
  if (collapse && window.innerWidth < 992) {
    collapse.style.display = 'none'
    isMenuOpen.value = false
  }
})

// Debug
if (process.client) {
  watch(destinations, (val) => {
    if (val.length) console.log('Destinations loaded:', val)
  }, { immediate: true })
}
</script>

<style>
.logo {
  height: 40px;
}
.image-loading {
  opacity: 0.5;
}
.dropdown-item a {
  text-decoration: none !important;
  color: #0d2d52;
  display: block;
  width: 100%;
  padding: 0.25rem 1rem;
}
.dropdown-item a:hover {
  background-color: #f8f9fa;
}

/* Mobile collapse hidden */
@media (max-width: 991.98px) {
  #navbarCollapse {
    display: none;
  }
}
</style>
