// flyfrontend/src/app/contact/page.tsx
'use client';

import { useEffect, useState } from 'react';
import MainLayout from '@/components/layouts/MainLayout';
import CountrySelector from '@/components/CountrySelector';
import { useContactStore } from '@/stores/contact';

export default function ContactPage() {
	const contactStore = useContactStore();
	const [form, setForm] = useState({
		name: '',
		email: '',
		phone: '',
		phoneDialCode: '+971',
		subject: '',
		message: '',
		contact_category_id: '',
	});

	useEffect(() => {
		contactStore.fetchCategories();
	}, [contactStore]);

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault();
		await contactStore.submitContact({
			...form,
			phone: `${form.phoneDialCode}${form.phone}`,
			contact_category_id: form.contact_category_id,
		});
		if (contactStore.success) {
			setForm({ name: '', email: '', phone: '', phoneDialCode: '+971', subject: '', message: '', contact_category_id: '' });
			alert('Message sent successfully!');
		}
	};

	return (
		<MainLayout>
			<main className="contact-wrapper">
				<div className="container">
					<div className="row g-5 align-items-start">
						<div className="col-lg-5">
							<div className="row">
								<div className="col-md-6">
									<div className="contact-card">
										<i className="bi bi-envelope" />
										<div>
											<h6>Email</h6>
											<a href="mailto:contact@ClickHospitals.com">contact@ClickHospitals.com</a>
										</div>
									</div>
								</div>
								<div className="col-md-6">
									<div className="contact-card">
										<i className="bi bi-telephone" />
										<div>
											<h6>Call us</h6>
											<a href="tel:+17344475890">+1(734)-447-5890</a>
										</div>
									</div>
								</div>
							</div>
							<img src="/assets/img/contact.png" alt="Patients at reception" className="contact-image mt-3" />
						</div>
						<div className="col-lg-7">
							<div className="contact-form-section">
								<h1>We&apos;re here to help you find your treatment worldwide</h1>
								<p>Have a question? We look forward to hearing from you.</p>
								<form onSubmit={handleSubmit}>
									<div className="row g-4">
										<div className="col-md-6">
											<label htmlFor="name" className="form-label">Name</label>
											<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} type="text" className="form-control" id="name" placeholder="Alex White" required />
										</div>
										<div className="col-md-6">
											<label htmlFor="email" className="form-label">Email</label>
											<input value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} type="email" className="form-control" id="email" placeholder="example@gmail.com" required />
										</div>
										<div className="col-md-6">
											<label htmlFor="phone" className="form-label">Phone</label>
											<div className="phone-input-wrapper-new d-flex gap-2">
												<CountrySelector value={form.phoneDialCode} onChange={(dialCode) => setForm({ ...form, phoneDialCode: dialCode })} />
												<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value.replace(/[^0-9]/g, '') })} type="text" className="form-control phone-input-field" id="phone" placeholder="Phone number" maxLength={15} />
											</div>
										</div>
										<div className="col-md-6">
											<label htmlFor="category" className="form-label">Category</label>
											<select value={form.contact_category_id} onChange={(e) => setForm({ ...form, contact_category_id: e.target.value })} className="form-select" id="category" required>
												<option value="">Select a category</option>
												{contactStore.categories.map((cat) => (
													<option key={cat.id} value={cat.id}>{cat.name}</option>
												))}
											</select>
										</div>
										<div className="col-12">
											<label htmlFor="subject" className="form-label">Subject</label>
											<input value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} type="text" className="form-control" id="subject" placeholder="Type subject here" required />
										</div>
										<div className="col-12">
											<label htmlFor="message" className="form-label">Message</label>
											<textarea value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} className="form-control" id="message" placeholder="Type your message here..." required />
										</div>
										<div className="col-12 mt-5">
											<button type="submit" className="btn btn-primary submit-btn" disabled={contactStore.loading}>
												{contactStore.loading ? 'Submitting...' : 'Submit'}
											</button>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</main>
		</MainLayout>
	);
}

// app/pages/contact.vue
<template>
    <main class="contact-wrapper">
        <div class="container">
            <div class="row g-5 align-items-start">
                <!-- Left Column -->
                <div class="col-lg-5 ">
                    <div class="row">
                        <div class="col-md-6 col-lg-6">
                            <div class="contact-card">
                                <Icon name="mdi:envelope-outline"></Icon>
                                <div>
                                    <h6>Email</h6>
                                    <a href="mailto:contact@flyhospitals.com">
                                        contact@ClickHospitals.com
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-6">
                            <div class="contact-card">
                                <Icon name="mdi:telephone"></Icon>
                                <div>
                                    <h6>Call us</h6>
                                    <a href="tel:+17344475890">
                                        +1(734)-447-5890
                                    </a>
                                </div>
                            </div>
                        </div>

                    </div>
                    <img src="~/assets/img/contact.png" alt="Patients at reception" class="contact-image mt-3">
                </div>
                <!-- Right Column -->
                <div class="col-lg-7">
                    <div class="contact-form-section">
                        <h1>We're here to help you find your treatment worldwide</h1>
                        <p>Have a question? We look forward to hearing from you. Or are you a medical provider looking
                            to list with us? Just click the Add Your Clinic button in the top-right corner, to create
                            your profile today.</p>
                        <form @submit.prevent="handleSubmit">
                            <div class="row g-4">
                                <div class="col-md-6">
                                    <label for="name" class="form-label">Name</label>
                                    <input v-model="form.name" type="text" class="form-control" id="name"
                                        placeholder="Alex White">
                                </div>

                                <div class="col-md-6">
                                    <label for="email" class="form-label">Email</label>
                                    <input v-model="form.email" type="email" class="form-control" id="email"
                                        placeholder="example@gmail.com">
                                </div>

                                <div class="col-md-6">
                                    <label for="phone" class="form-label">Phone</label>
                                    <div class="phone-input-wrapper-new">
                                        <CountrySelector
                                            v-model="form.phoneDialCode"
                                            default-country-code="AE"
                                            @country-changed="onCountryChanged"
                                        />
                                        <input
                                            v-model="form.phone"
                                            type="text"
                                            class="form-control phone-input-field"
                                            id="phone"
                                            placeholder="Phone number"
                                            inputmode="numeric"
                                            pattern="[0-9]*"
                                            oninput="this.value = this.value.replace(/[^0-9]/g, '');"
                                            maxlength="15"
                                        >
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <label for="category" class="form-label">Category</label>
                                    <select v-model="form.contact_category_id" class="form-select" id="category"
                                        name="category">
                                        <option disabled value="">Select a category</option>
                                        <option v-for="cat in contactStore.categories" :key="cat.id" :value="cat.id">
                                            {{ cat.name }}
                                        </option>
                                    </select>
                                </div>

                                <div class="col-12">
                                    <label for="subject" class="form-label">Subject</label>
                                    <input v-model="form.subject" type="text" class="form-control" id="subject"
                                        placeholder="Type subject here">
                                </div>

                                <div class="col-12">
                                    <label for="message" class="form-label">Message</label>
                                    <textarea v-model="form.message" class="form-control" id="message"
                                        placeholder="Type your message here..."></textarea>
                                </div>

                                <div class="col-12 mt-5">
                                    <button type="submit" class="btn btn-primary submit-btn">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>

            </div>
        </div>
    </main>
</template>
<script setup lang="ts">
import { reactive } from 'vue'
import { useContactStore } from '~/stores/contact'

const contactStore = useContactStore()

// ✅ Load categories on SSR + CSR
await contactStore.fetchCategories()

// ✅ Reactive form data (must match API payload exactly)
const form = reactive({
    name: '',
    email: '',
    phone: '',
    phoneDialCode: '+971', // Country dial code
    subject: '',
    message: '',
    contact_category_id: '' // will hold category ID from API
})

// ✅ Handle country change
const onCountryChanged = (country: any) => {
    form.phoneDialCode = country.dialCode
    console.log('Country changed to:', country.name, country.dialCode)
}

// ✅ Submit handler
const handleSubmit = async () => {
    // Combine dial code and phone for the API
    const submissionData = {
        ...form,
        phone: `${form.phoneDialCode}${form.phone}`
    }
    
    const res = await contactStore.submitContact(submissionData)

    if (contactStore.success) {
        alert('Message sent successfully ✅')

        // Reset form after success
        form.name = ''
        form.email = ''
        form.phone = ''
        form.phoneDialCode = '+971'
        form.subject = ''
        form.message = ''
        form.contact_category_id = ''
    } else {
        alert('Error: ' + contactStore.error)
    }
}
</script>
